### ISSUE TITLE
Migrate to kedro>=0.17.0

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#144]
## Description
The new `kedro==0.17.0` version is out and comes with [its share of breaking changes](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#release-0170).

## Context
It is important to keep the plugin up to date with kedro to avoid deprecation and increase adoption. It will also enable to adopt some highly demanded feature (e.g. #92 and maybe #124)

## Possible Implementation

Most of the breaking changes comes from the `context` which is now contained in a KedroSession object. It must be updated all over the codebase. 

The release notes must be read in details to see if some other changes are needed.

## TODO

- [x] Bump requirements
- [x] Change the config_dir fixture accordingly to the new template for the tests
- [x] utils:
  - [x] Update ``_is_kedro_project`` to check for existence of a "[tool.kedro]" section in pyproject.toml. See [kedro ProjectMetaData _is_project()](https://github.com/quantumblacklabs/kedro/blob/1bb5f4be6fc4e6ef7a5a9480131cbce4582385c9/kedro/framework/startup.py)
  - [x] Update ``_get_project_globals`` to retrieve info from pyproject.toml See [kedro ProjectMetaData _get_project_metadata()](https://github.com/quantumblacklabs/kedro/blob/1bb5f4be6fc4e6ef7a5a9480131cbce4582385c9/kedro/framework/startup.py)
- [x] config:
  - [x] Update ``validate_uri`` which should dynamically get project_path from KedroSession
  - [x] Update  ``setup`` to avoid avoid passing context as argument (retrieve from KedroSession inside the function)
- [x] cli: 
  - [x] Replace call to `load_context()` by `KedroSession.create()`
  - [x] Update to the new utility to retrieve metadata
- [x] hooks: 
  - [x] Replace calls to `load_context()` by `get_current_session()`
- [x] Update all tests to replace calls to `load_context()` by `KedroSession.create()`
- [ ] Update documentation

**Comment by Galileo-Galilei** [comment]
If anyone wants to try the version with 0.17 (@arnaldog12, sorry to ping directly but if you want to be a beta tester it will help ;p), feel free to install directly the plugin from the feature/compatibility-0.17 branch, it should already work and will be released within few weeks.

```console
pip install --upgrade git+https://github.com/Galileo-Galilei/kedro-mlflow.git@feature/compatibility-0.17
```

**Comment by arnaldog12** [comment]
Hi, @Galileo-Galilei 
I'll try it in the next few days. Thanks!

**Comment by arnaldog12** [comment]
Hi, @Galileo-Galilei 
I have just tested the `kedro-mlflow` version you sent to me in an existing project. It worked very well!
Good job! Congrats on that!

I can also take a look at the PR if you want. Just let me know.
Best regards,

**Comment by Galileo-Galilei** [comment]
Thank you for the test! It would be very nice if you find time to review the code, the more eyes on it, the better the result! (note that I am still making some minor updates to the PR to improve docs and tests, but the core code should be already quite stable ).

**Comment by Galileo-Galilei** [comment]
I reopen the issue for future works, but currrently: 

- "kedro-mlflow==0.6.0" has been published on PyPI today, and is fully compatible with kedro==0.17.0
- I've just published on master a version which is compatible with kedro>=0.17.1, so anyone who is interested can install directly from github with: 

```console
pip install --upgrade git+https://github.com/Galileo-Galilei/kedro-mlflow.git
```

Any beta tester is warmly welcome!
